<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ATMECSINLT-060" failures="1" tests="1" name="SampleTest" time="31.946" errors="0" timestamp="10 Nov 2020 15:17:26 GMT">
  <testcase classname="com.atmecs.automationAspireportal.testscript.TC02_Manager_ActionReject" name="EmployeePage" time="16.905">
    <failure type="java.lang.AssertionError" message="expected [Reason for rejection] but found []">
      <![CDATA[java.lang.AssertionError: expected [Reason for rejection] but found []
at com.atmecs.falcon.automation.verifyresult.VerificationManager.verifyString(VerificationManager.java:250)
at com.atmecs.automationAspireportal.testscript.TC02_Manager_ActionReject.EmployeePage(TC02_Manager_ActionReject.java:85)
at com.atmecs.automationAspireportal.runner.TestNGRunner.main(TestNGRunner.java:61)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- EmployeePage -->
</testsuite> <!-- SampleTest -->
